'use client';

import type { Metadata } from 'next';
import { Inter, Inconsolata, Tomorrow } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'styled-components';
import { Provider, useSelector } from 'react-redux';
import themeSlice from './store/slices/themeSlice';
import { store } from './store';

const inconsolata = Tomorrow({
    subsets: ['latin'],
    weight: ['400', '600']
});

// export const metadata: Metadata = {
//     title: 'Complex',
//     description: 'Generated by create next app'
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <Provider store={store}>
                <body className={inconsolata.className}>{children}</body>
            </Provider>
        </html>
    );
}
