'use client';

import type { Metadata } from 'next';
import { Inter, Inconsolata, Tomorrow, Ubuntu } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import { store } from '../store';
import Header from '../containers/Header';
import { AppThemeProvider } from './AppThemeProvider';
import Footer from '../containers/Footer';

const inconsolata = Ubuntu({
    subsets: ['latin'],
    weight: ['300', '500']
});

// export const metadata: Metadata = {
//     title: 'Complex',
//     description: 'Generated by create next app'
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <Provider store={store}>
            <AppThemeProvider>
                <html lang="en">
                    <body className={inconsolata.className}>
                        <Header />
                        {children}
                        <Footer />
                    </body>
                </html>
            </AppThemeProvider>
        </Provider>
    );
}
